### PR TITLE
Reduce padding around inspector accordion

### PR DESCRIPTION
**Pull request by chipit24**
Fixes https://github.com/ProcessMaker/modeler/issues/688.

Before:
Screen Shot 2019-09-25 at 4 33 59 PM

After:
Screen Shot 2019-09-25 at 4 37 12 PM

### CODE REVIEW

**Comment by lisa-fehr** [comment]
It loses vertical alignment with the gears in the headers (ie: Configuration). Should those headers also be slimmed down?

**Comment by chipit24** [comment]
That padding there comes from a `.card-header` class, not a `.p-#` helper class. The issue simply mentions decreasing the number for the padding helper classes. Beyond that, I'm not sure what the end result should look like. @velkymx will have to confirm.

**Comment by lisa-fehr** [comment]
@chipit24 ah, it didn't sound that specific. I thought it would include everything in the inspector.

**Comment by chipit24** [comment]
I should have held off on creating a PR for this as "(py-3 to py-2, etc)" isn't very specific, and we're left making assumptions on what "etc" means here, especially since there's no design or any other information. These are the times when using our _definition of ready_ would help us.

I'll put this on hold for now until we get more clarification next week.

**Comment by chipit24** [comment]
Keep alignment consistent and reduce padding between icon and accordion header.

**Comment by chipit24** [comment]
Updated PR based on comments from standup:
Screen Shot 2019-09-30 at 2 58 09 PM

**Comment by lisa-fehr** [comment]
When I link vue form elements with processmaker, I'm not seeing the same alignment as the screenshot. But I do see a reduction in padding.

**Comment by chipit24** [comment]
@lisa-fehr It gets confusing with these changes; you might have to link form elements into modeler and then link modeler into processmaker. And then you might have to also link form elements into processmaker too. I had them both linked and padding showed up as expected.

**Pull request merged**
